### ISSUE TITLE
Compute sum of digits in all numbers from 1 to n

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#100]
## Given a number x, find sum of digits in all numbers from 1 to n.
Input: n = 5
Output: Sum of digits in numbers from 1 to 5 = 15

Input: n = 12
Output: Sum of digits in numbers from 1 to 12 = 51

Input: n = 328
Output: Sum of digits in numbers from 1 to 328 = 3241

**Comment by willdougadams** [comment]
Can I call dibs on this?  Looks like a good first PR for hacktoberfest :)
