### ISSUE TITLE
Game of Sum Dynamic Programming Problem 

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#111]
![alt text](http://img.blog.csdn.net/20170726175911548?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvYmxlc3NMWkgwMTA4/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by mory91** [comment]
done #119

**Comment by sanchaymittal** [comment]
Is this still open?

**Comment by matthewsamuel95** [comment]
Yes, please explain the solution.

**Comment by sanchaymittal** [comment]
Yahh sure.

**Comment by OmarKimo** [comment]
Why is this issue still open?
Where is the code of this problem?
