### ISSUE TITLE
Square root of an integer

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#150]
### Implement int sqrt(int x).

Compute and return the square root of x, where x is guaranteed to be a non-negative integer.

Since the return type is an integer, the decimal digits are truncated and only the integer part of the result is returned.

Given an integer x, find square root of it. If x is not a perfect square, then return floor(√x).

**Examples**:
Input: x = 4
Output: 2

Input: x = 11
Output: 3

**Comment by rishu08** [comment]
can I solve it?

**Comment by zbarbezat** [comment]
Where would I place this in your existing file structure?

**Comment by matthewsamuel95** [comment]
> can I solve it?

Yes.

**Comment by matthewsamuel95** [comment]
> Where would I place this in your existing file structure?

Math.

**Comment by dreamerHarshit** [comment]
@matthewsamuel95 i want to solve this problem using binary search

**Comment by matthewsamuel95** [comment]
> @matthewsamuel95 i want to solve this problem using binary search

Great lets see it!

**Comment by dreamerHarshit** [comment]
@matthewsamuel95  raised PR in Python
