### ISSUE TITLE
Write a program to calculate pow(x,n)

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#159]
Implement pow(x, n), which calculates x raised to the power n (x^n).

Examples 
Input: 2.00000, 10
Output: 1024.00000

### **Consider negative exponents**

**Comment by bsztankovacs** [comment]
I can handle this

**Comment by Abhigupta4981** [comment]
@matthewsamuel95 i can do this

**Comment by thecoderkd** [comment]
Hey can I work on this?

**Comment by matthewsamuel95** [comment]
Yes without built in functions.

**Comment by Abhigupta4981** [comment]
in which directory and with what filename do we have to write this code ?

**Comment by matthewsamuel95** [comment]
Math/power/{ur file} 

ur file can be any name

**Comment by Abhigupta4981** [comment]
ok thanx

**Comment by singh-sarabjeet** [comment]
#166 Fixed

**Comment by dreamerHarshit** [comment]
@matthewsamuel95  i have raised PR for this issue in python

**Comment by Meg2tron** [comment]
Can I do This??

**Comment by Meg2tron** [comment]
Done at mouri11/ACM-ICPC-Algorithms/Math

**Comment by manan012** [comment]
I want to work on it.
