### ISSUE TITLE
Count all possible paths from top left to bottom right of a mXm matrix

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#192]
The problem is to count all the possible paths from top left to bottom right of a mXm matrix with the constraints that from each cell you can either move only to right or down

Example

> 
Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

> 

![](https://projecteuler.net/project/images/p015.gif)

**Comment by RedwanKhaled** [comment]
@matthewsamuel95 what is the size of M?

**Comment by matthewsamuel95** [comment]
variable sized range can be from 1 - 50

**Comment by Vishal1541** [comment]
@matthewsamuel95 I would like to work on this.
