### ISSUE TITLE
2 Sum 

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#193]
Given an array of integers, return indices of the two numbers such that they add up to a specific target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

Example:

Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].

**Comment by ashish4321** [comment]
I am working on it

**Comment by Meg2tron** [comment]
I am also working on this

**Comment by Meg2tron** [comment]
Done
