### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#233]
Give instructions how to follow the file structure and create a pull request

**Comment by matthewsamuel95** [comment]
@swastikbanerjee07

**Comment by swastikbanerjee07** [comment]
Could please elaborate what do you mean by "following the file structure"?

**Comment by matthewsamuel95** [comment]
On how Math problems should go in  Math/{title of problem}/{ur file name}

make sure ur file name has a .cpp or .c or .java or what ever language 

and if a title of a problem already exists and u have another solution create in the same subfolder

if you have a different language used put in Math/{name of problem}/{language}/{file name}

if the topic is not math if its sorting put in Sorting/... as such
