### ISSUE TITLE
Write a program to calculate pow(x,n)

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#236]
### **Consider values for negative n**

Implement pow(x, n), which calculates x raised to the power n (x^n).

Examples
Input: 2, -2 
Output : 0.25

Input: 2.00000, 10
Output: 1024.00000

_Push code to Math/Power/{ur file}_

**Comment by devyboy** [comment]
i got this one

**Comment by codeShaurya** [comment]
I got this one..

**Comment by Meg2tron** [comment]
Done
