### ISSUE TITLE
Group Anagrams

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#267]
### **Given an array of strings, group anagrams together.**
```
Example
Input: ["eat", "tea", "tan", "ate", "nat", "bat"],
Output:
[
  ["ate","eat","tea"],
  ["nat","tan"],
  ["bat"]
]
```
_Place code in String subfolder_

**Comment by gustafsilva** [comment]
Hello @matthewsamuel95, i would like to do this task. :+1: 
Can the code be written in `C++` or `Python`, or in both languages?
I noticed that `is_anagram` function already exists in C++ and Python.

**Comment by matthewsamuel95** [comment]
Any language or both is great.

**Comment by ChintuYadav** [comment]
@matthewsamuel95 Is Javascript fine?
