### ISSUE TITLE
Implement Stack using Queues

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#278]
![](https://www.geeksforgeeks.org/wp-content/uploads/Stack-Queue.png)

We are given a Queue data structure that supports standard operations like enqueue() and dequeue(). We need to implement a Stack data structure using only instances of Queue and queue operations allowed on the instances.

_Place in data structures_

### **Opposite of Implement Queue using Stacks**

**Comment by WizardOfArc** [comment]
I'll try this one if it's okay

**Comment by dreamerHarshit** [comment]
@matthewsamuel95 i want to work on this.

**Comment by dreamerHarshit** [comment]
@matthewsamuel95  raised PR for this.
