### ISSUE TITLE
Implement Queue using Stacks

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#279]
![](https://www.geeksforgeeks.org/wp-content/uploads/Stack-Queue.png)

 We are given a stack data structure with push and pop operations, the task is to implement a queue using instances of stack data structure and operations on them.

_Place in data structures_

### **Opposite of Implement Stack using Queues**

**Comment by vishal-wadhwa** [comment]
Hi!
I'd like to take this up for a cpp implementation. Should I go ahead?

**Comment by vishal-wadhwa** [comment]
Hi!
I'd like to take this up for a cpp implemetation. Should I go ahead?

**Comment by matthewsamuel95** [comment]
Yes
