### ISSUE TITLE
add .gitignore

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#301]
include .txt .in .out a.out .pyc .class and others  please work together and form one great git ignore 
@RCMainak @dreamerHarshit @BlackVS and open to others
 
put in root dir

**Comment by AntonStrand** [comment]
I can make one if you want.

**Comment by matthewsamuel95** [comment]
great!

**Comment by au12113** [comment]
Can I join this issue?

**Comment by matthewsamuel95** [comment]
Yes please collab with others

**Comment by RCMainak** [comment]
Hey @matthewsamuel95, can you suggest where can we collab? I can see how multiple PR's are increasingly becoming a pain point for you

I would suggest you to accept one PR then continue improving the gitignore file, it's one way to avoid duplicate PR's for the same issue.

**Comment by dreamerHarshit** [comment]
> Hey @matthewsamuel95, can you suggest where can we collab? I can see how multiple PR's are increasingly becoming a pain point for you
> 
> I would suggest you to accept one PR then continue improving the gitignore file, it's one way to avoid duplicate PR's for the same issue.

+1

**Comment by matthewsamuel95** [comment]
@dreamerHarshit  @RCMainak @BlackVS  @au12113 @AntonStrand  @archie9211  @RCMainak  https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/projects/1

**Comment by dreamerHarshit** [comment]
same here, i'm also not able to create new card @matthewsamuel95

**Comment by matthewsamuel95** [comment]
one sec, let me figure something out

**Comment by matthewsamuel95** [comment]
@dreamerHarshit @RCMainak @BlackVS @au12113 @AntonStrand @archie9211 @RCMainak collab/chat/write one massive gitignore here (will give credit in gitignore to all who participate open to others): 

https://codeshare.io/5wQ1r7
