### ISSUE TITLE
Greedy Algorithms 

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#312]
anyone have any cool greedy algos in mind

**Comment by cdeepanshu** [comment]
Yes, I have an algo whose statement is  as follow:
"Suppose you are given 'n' activities with their start and finish times. Select the maximum number of activities that can be performed by a single person, assuming that a person can only work on a single activity at a time."
I want to work on it

**Comment by matthewsamuel95** [comment]
great! create readme and follow file structure

**Comment by cdeepanshu** [comment]
Ok
