### ISSUE TITLE
implement linked list

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#321]
place in DS

**Comment by Slakscape** [comment]
Singly, doubly, circular?

**Comment by dnguneratne** [comment]
Can I take this? I can do it in C++

**Comment by mitesh1612** [comment]
Can I take this? I can do it in C, C++, Python, Java

**Comment by regalstreak** [comment]
Can I take this? I can do it in Hindi, Marathi and Sanskrit as well
