### ISSUE TITLE
Number of Islands

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#336]
Given a 2d grid map of '1's (land) and '0's (water), count the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.

EXAMPLES:

```

Example 1:

Input:
11110
11010
11000
00000

Output: 1
Example 2:

Input:
11000
11000
00100
00011

Output: 3
```

**Comment by aishwr** [comment]
I have completed the solution.

Which folder should I put the solution in?

**Comment by matthewsamuel95** [comment]
DP
