### ISSUE TITLE
fix grammer in CONTRIBUTING.md

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#338]
at the end of https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/blob/master/CONTRIBUTING.md

there is a note , need to edit this part to be very clear

**Comment by andrew-kwong** [comment]
On it!

**Comment by matthewsamuel95** [comment]
great!

**Comment by ramlaxman** [comment]
can you please take a look at https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/pull/344#issue-220261251 and merge it.
Thanks !
