### ISSUE TITLE
Minimum Path Sum

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#340]
Given a m x n grid filled with non-negative numbers, find a path from top left to bottom right which minimizes the sum of all numbers along its path.

You can only traverse down, right and diagonally lower cells from a given cell.

![](https://www.geeksforgeeks.org/wp-content/uploads/dp.png)
**The path with minimum cost is highlighted in the following figure. The path is (0, 0) –> (0, 1) –> (1, 2) –> (2, 2). The cost of the path is 8 (1 + 2 + 2 + 3).**
![](https://www.geeksforgeeks.org/wp-content/uploads/dp2.png)

**Comment by sudesh1611** [comment]
I would like to do this program. Where should I put this solution??

**Comment by matthewsamuel95** [comment]
DP
