### ISSUE TITLE
edit grammar in README.md

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#357]
fix grammar in README.md and make it very clear 

few things to fix:

- remove : "nerds"

- reword : Then what is the purpose of ACM-ICPC Algorithms ?

- and more you may notice

**Comment by Alexius08** [comment]
Let me take care of this one.

**Comment by matthewsamuel95** [comment]
open to all many correct methods of fixing

**Comment by matthewsamuel95** [comment]
@Alexius08 can u re word/ or remove this as well:

If you know algorithms but don't know a particular language, this can help you understand ICPC algorithms in any language.
