### ISSUE TITLE
edit README.md

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#361]
re word/ or remove :

- If you know algorithms but don't know a particular language, this can help you understand ICPC algorithms in any language.

- Then what is the purpose of ACM-ICPC Algorithms ? (re word if possible)

- etc...

**Comment by m4tr1k** [comment]
Hi @matthewsamuel95, when you say re word you mean rewrite to another thing?

**Comment by matthewsamuel95** [comment]
either work great!

**Comment by m4tr1k** [comment]
I'll try to do my best, not now because I can't, but maybe tomorrow!

**Comment by Apoorva-13** [comment]
hi can i take up this issue? But need some more clarity as to what is to be done?
