### ISSUE TITLE
Evolving README.md

### ISSUE THREAD

**Issue by OmarKimo** [matthewsamuel95/ACM-ICPC-Algorithms#388]
Make a path hierarchy below each topic in README.md.
(i.e. below the link of Math in README, add all the topics in it linked to their source code and of course, they should be indented correctly.)
Example:
* [Item 1](http://github.com)
* [Item 2](http://github.com)
  * [Item 2a](http://github.com)
  * [Item 2b](http://github.com)

**Comment by OmarKimo** [comment]
> Sorry i didn't get you. Can you please elaborate.

I want to make like a table of contents in README.md just as I showed in the example.
* [Math](https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/tree/master/Math)
  * [Matrix Power](https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/blob/master/Math/Matrix_Power/matrix_power.cpp)
  * [Factorization](https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/blob/master/Math/Factorization/findFactors.cpp)
and so on.

**Comment by Artistic18** [comment]
Is it only for the Math directory or for every directory?

**Comment by OmarKimo** [comment]
Of course, for every directory [topic].

**Comment by Artistic18** [comment]
Can i work on this?

**Comment by OmarKimo** [comment]
Of course, yes!
