### ISSUE TITLE
Graph Algorithms needed to be implemented 

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#55]
- [x] - Dijkstra
 
- [x] - Kruskal
 
- [x] - Prims
 
- [x] - Topological Sort

- [x] - Floyd Warshall

- [x] - Dial’s

- [x] - Johnson’s

- [x] - Tarjan’s

**Comment by jakubbogucki** [comment]
Are you just creating database of algorithms or do you have some point in this?
