### ISSUE TITLE
Sorting and Searching algorithms

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#6]

**Comment by Danianny** [comment]
Any sorting and searching algorithms? 

Also, any language preference?

**Comment by matthewsamuel95** [comment]
Yes, any algorithm. I prefer C++, Java and Python. But I am open to all languages.

**Comment by Danianny** [comment]
Okie dokie. Are you creating folders for this issues or can I just send it to the master?

**Comment by matthewsamuel95** [comment]
I just created the folders for these. Push it to them.
