### ISSUE TITLE
Subset Sum Problem

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#75]
# Subset Sum Problem

Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum.

Examples: set[] = {3, 34, 4, 12, 5, 2}, sum = 9
Output:  True  //There is a subset (4, 5) with sum 9.

**Comment by skydans** [comment]
I added a recursive solution for subset sum at #77
