### ISSUE TITLE
Greedy Algorithms

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#8]

**Comment by 96mohitm** [comment]
Greedy Algorithms like Kruskal’s Minimum Spanning Tree Algorithm

**Comment by crunchcrackle** [comment]
Any other ones I could implement here? Dijkstra's, Prim's? I'm new to contributing to open source so I'd love to start with this!

**Comment by matthewsamuel95** [comment]
Any would be great! Also try Dial’s Algorithm.

**Comment by eopXD** [comment]
@96mohitm @crunchcrackle I think algos such as MST or Dijskstra, prim are under the category of graph algorithms.
@matthewsamuel95 may be greedy methods can be other cases of the remaining category, you may need to label it out someway? In my opinion greedy is simply a concept.

**Comment by matthewsamuel95** [comment]
Create a new issue to fix this confusion.
